#!/bin/sh
# Config
bspc config border_width        2
bspc config window_gap         12

bspc config focused_border_color    "#$(getXresColor foreground)"
bspc config normal_border_color     "#$(getXresColor background)"
bspc config presel_border_color     "#$(getXresColor color15)"

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# Workspaces
bspc monitor -d 000 001 010 011 100 101 110 111

# Rules
bspc rule -a Firefox desktop=^1

bspc rule -a feh floating=on
bspc rule -a mpv floating=on
bspc rule -a zathura floating=on
bspc rule -a Gimp-2.8 floating=on

# Status Bar
~/.config/bspwm/bin/panel &

#
# Startup
#

# Terminal daemon
command -v urxvt >/dev/null 2>&1 && urxvtd -q -o -f

# Notification daemon
command -v dunst >/dev/null 2>&1 && dunst &

# Background
command -v feh >/dev/null 2>&1 && ~/.fehbg
