#!/bin/sh
# Config
bspc config border_width        2
bspc config window_gap          12

bspc config focused_border_color    "#$(getXresColor foreground)"
bspc config active_border_color     "#$(getXresColor color8)"
bspc config normal_border_color     "#$(getXresColor background)"
bspc config presel_feedback_color   "#$(getXresColor foreground)"

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focus_follows_pointer   true
bspc config pointer_follows_monitor true

# Workspaces
if xrandr -q | grep "VGA-0 connected" > /dev/null 2>&1; then
    bspc monitor LVDS --rename 0 --reset-desktops 000 001 010 011
    bspc monitor VGA-0 --rename 1 --reset-desktops 100 101 110 111
else
    bspc monitor --rename 0 000 001 010 011 100 101 110 111
fi

bspc monitor 0 --focus

# Rules
bspc rule -a Firefox desktop='^1'

bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a zathura state=floating
bspc rule -a Gimp-2.8 state=floating

# Status Bar
~/.config/bspwm/bin/panel &

#
# Startup
#

# Terminal daemon
command -v urxvt >/dev/null 2>&1 && urxvtd -q -o -f

# Notification daemon
command -v dunst >/dev/null 2>&1 && dunst &

# Background
command -v feh >/dev/null 2>&1 && ~/.fehbg
