#!/bin/bash

set -e

PANEL_FIFO="/tmp/bspwm.fifo"
DIR="${HOME}/.config/bspwm"

FG="#$(getXresColor foreground)"
BG="#$(getXresColor background)"

if [[ $(pgrep -cx panel) -gt 1 ]]; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap "trap - TERM; kill 0" INT TERM QUIT EXIT

[[ -e ${PANEL_FIFO} ]] && rm ${PANEL_FIFO}
mkfifo ${PANEL_FIFO}

bspc config top_padding 10

conky -c ${DIR}/conkyrc > ${PANEL_FIFO} &
bspc control --subscribe > ${PANEL_FIFO} &

cat ${PANEL_FIFO} \
    | ${DIR}/workspace \
    | lemonbar -g "x10++" -F "${FG}" -B "${BG}" \
        -f "-*-stlarch-medium-*-normal-*-*-*-*-*-c-*-*-*"\
        -f "-*-cure-medium-*-normal-*-*-*-*-*-*-*-*-*"

wait
