#!/bin/bash

SEP="#FF$(getXresColor color3)"
HFG="#FF$(getXresColor color15)"
NFG="#FF$(getXresColor foreground)"

while read -r line; do
    case ${line} in
        C*) #clock output
            clock="${line#?}"
            ;;
        S*) #system information
            sys_info="${line#?}"
            ;;
        W*) #bspwm internal state
            wm_infos=""
            IFS=":"
            set -- ${line#?}
            while [ $# -gt 0 ]; do
                item=${1}
                name=${item#?}
                case $item in
                    [OFU]*) wm_infos+=" %{F${HFG}}\uE001%{F-} " ;;
                    u*) wm_infos+=" %{F${NFG}}\uE001%{F-} " ;;
                    o*) wm_infos+=" \uE001 " ;;
                    f*) wm_infos+=" \uE000 " ;;
                esac
                shift
            done
            ;;
        esac
    printf "%b %b %b\n" \
        "%{l}${clock}" \
        "%{c}%{F${SEP}}::%{F-}  ${wm_infos}  %{F${SEP}}::%{F-}" \
        "%{r}${sys_info}"
done
