#! /bin/bash

#
# WM Setup
#

# tags/workspaces/desktops
if xrandr --query | grep 'HDMI1 connected' >/dev/null 2>&1 ; then
    bspc monitor eDP1 --focus --reset-desktops 000 001 010 011
    bspc monitor HDMI1 --reset-desktops 100 101
else
    bspc monitor --focus --reset-desktops 000 001 010 011 100 101
fi
bspc config pointer_follows_monitor true

# border & gap
bspc config border_width            5
bspc config window_gap              10

# layout
bspc config split_ratio             0.5
bspc config borderless_monocle      false
bspc config gapless_monocle         false

# color theme
bspc config normal_border_color     "#4C566A"       # Nord3
bspc config focused_border_color    "#ECEFF4"       # Nord6
bspc config active_border_color     "#E5E9F0"       # Nord5
bspc config presel_feedback_color   "#434c5e"       # Nord2

# rules
bspc rule --add firefox desktop='^1'
bspc rule --add Chromium desktop='^1'

bspc rule --add firefox:Places state=floating
bspc rule --add firefox:Toolkit state=floating
bspc rule --add firefox:firefox state=floating

bspc rule --add Pinentry-gtk2 state=floating
bspc rule --add Gimp state=floating
bspc rule --add mpv state=floating
bspc rule --add feh state=floating

# desktop layout
bspc desktop 000 --layout monocle

#
# Autostart
#

# wallpaper
command -v feh >/dev/null 2>&1 && $HOME/.fehbg
