#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}


# announce reload
hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# Use the super key as the main modifier
Mod=Mod4

# reload wm
hc keybind $Mod-Escape reload

# exit wm
hc keybind $Mod-Shift-Escape quit

# multi monitor setup
#hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
#hc detect_monitors

# cycle through monitors
hc keybind $Mod-Home cycle_monitor

# set default layout
hc set default_frame_layout 3

# create tags
tag_names=( {1..6} )
tag_keys=( {1..6} )
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# set custom layout
for tag in 1 5 6; do
    hc load ${tag} '(clients max:0)'
done

# tag modes
hc keybind $Mod-F2 floating toggle
hc keybind $Mod-F3 pseudotile toggle
hc keybind $Mod-F4 fullscreen toggle

# cycle through tags
hc keybind XF86Forward      use_index +1 --skip-visible
hc keybind XF86Back         use_index -1 --skip-visible
hc keybind $Mod-apostrophe  use_previous

# splitting frames
hc keybind $Mod-F5 split bottom    0.5
hc keybind $Mod-F6 split right     0.5
hc keybind $Mod-F7 split explode
hc keybind $Mod-F8 remove

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# layouting
hc keybind $Mod-F9  set_layout vertical
hc keybind $Mod-F10 set_layout horizontal
hc keybind $Mod-F11 set_layout max
hc keybind $Mod-F12 set_layout grid
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
    or , and . compare tags.focus.curframe_wcount = 2 \
    . cycle_layout +1 vertical horizontal max vertical grid \
    , cycle_layout +1

# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# closing clients
hc keybind $Mod-w close_or_remove

# cycle through clients
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1

# move to urgent client
hc keybind $Mod-semicolon jumpto urgent

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc attr theme.background_color "#$(getXresColor.sh color7)"

hc attr theme.border_width 9
hc attr theme.inner_width 4
hc attr theme.outer_width 5
hc attr theme.active.inner_color "#$(getXresColor.sh color15)"
hc attr theme.active.outer_color "#$(getXresColor.sh color8)"
hc attr theme.normal.inner_color "#$(getXresColor.sh color7)"
hc attr theme.normal.outer_color "#$(getXresColor.sh color0)"
hc attr theme.urgent.inner_color "#$(getXresColor.sh color1)"
gc attr theme.urgent.outer_color "#$(getXresColor.sh color0)"

# settings
hc set always_show_frame 1

hc set frame_border_width 3
hc set frame_border_active_color "#$(getXresColor.sh color15)"
hc set frame_border_normal_color "#$(getXresColor.sh color7)"
hc set frame_bg_active_color "#$(getXresColor.sh color8)"
hc set frame_bg_normal_color "#$(getXresColor.sh color0)"

hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_active_opacity 75
hc set frame_normal_opacity 50

hc set frame_gap 5
hc set frame_padding 2
hc set window_gap 10

hc set smart_frame_surroundings 1
hc set smart_window_surroundings 0
hc set mouse_recenter_gap 0
hc set raise_on_focus_temporarily 1

# nice ascii tree
herbstclient set tree_style '╾│ ├└╼─┐'

# remove all existing keybindings
hc unrule -F

# normally focus new clients
hc rule focus=on

# tag rules
hc rule class=Firefox tag=1
hc rule class=Chromium tag=1
hc rule class=Opera tag=1

# window rules
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule not windowrole=browser class=Firefox pseudotile=on

# behaviour rules
hc rule class=mpv pseudotile=on
hc rule class=feh pseudotile=on
hc rule class=Wine pseudotile=on
hc rule class=Pinentry pseudotile=on
hc rule class=Gcr-prompter pseudotile=on

# unlock, just to be sure
hc unlock

# terminal emulator
hc keybind $Mod-Return spawn termite

# application launcher
hc keybind XF86Search spawn rofi -modi drun -show drun
hc keybind $Mod-XF86Search spawn rofi -show run

# volume keys
hc keybind XF86AudioLowerVolume spawn ponymix -N decrease 5
hc keybind XF86AudioRaiseVolume spawn ponymix -N increase 5
hc keybind XF86AudioMute        spawn ponymix -N toggle

# music player
hc keybind XF86AudioPlay        spawn playerctl play-pause
hc keybind $Mod-XF86AudioPlay   spawn playerctl stop
hc keybind XF86AudioPrev        spawn playerctl previous
hc keybind XF86AudioNext        spawn playerctl next

# lockscreen
hc keybind $Mod-XF86Mail spawn sxlock -f '-misc-ohsnap-medium-*-normal-*-11-*-*-*-*-*-*-*'

# info bar
hc keybind $Mod-F1 spawn ${HOME}/.config/herbstluftwm/bin/infobar.py

# tags notification
${HOME}/.config/herbstluftwm/bin/tags.py &

# set wallpaper
command -v feh >/dev/null 2>&1 && ~/.fehbg
